"""Unit tests for the host-resolver tracking in forwarder.py.

No engine or network is involved: layouts under a temporary directory mirror
the sidecar's read-only host binds (/host/etc, /host/run).
"""

import contextlib
import os
import tempfile
import unittest
from pathlib import Path

import forwarder
from forwarder import UpstreamTracker, load_upstreams, parse_resolv_conf


@contextlib.contextmanager
def make_layout():
    with tempfile.TemporaryDirectory(prefix="dns-test-") as name:
        base = Path(name)
        host_etc = base / "etc"
        run_systemd = base / "run" / "systemd" / "resolve"
        run_nm = base / "run" / "NetworkManager"
        host_etc.mkdir(parents=True)
        run_systemd.mkdir(parents=True)
        run_nm.mkdir(parents=True)
        yield base, host_etc, run_systemd, run_nm


def upstreams_of(host_etc, base):
    return load_upstreams(str(host_etc), str(base / "run"))


class ParseTests(unittest.TestCase):
    def test_nameservers_in_order_with_comments(self):
        text = (
            "# Generated by Docker Engine.\n"
            "nameserver 100.100.100.100\n"
            "search tailfc0df0.ts.net lan  # trailing comment\n"
            "nameserver fd7a:115c:a1e0::53\n"
            "options ndots:0\n"
        )
        self.assertEqual(
            parse_resolv_conf(text), ["100.100.100.100", "fd7a:115c:a1e0::53"]
        )

    def test_garbage_and_duplicates_ignored(self):
        text = (
            "nameserver not-an-ip\n"
            "nameserver 0.0.0.0\n"
            "nameserver 9.9.9.9 extra tokens\n"
            "nameserver 9.9.9.9\n"
            "nameserver 1.1.1.1\n"
        )
        self.assertEqual(parse_resolv_conf(text), ["9.9.9.9", "1.1.1.1"])

    def test_capped_at_three_preserving_order(self):
        text = "\n".join(f"nameserver 10.0.0.{i}" for i in range(1, 6))
        self.assertEqual(
            parse_resolv_conf(text), ["10.0.0.1", "10.0.0.2", "10.0.0.3"]
        )

    def test_empty(self):
        self.assertEqual(parse_resolv_conf(""), [])
        self.assertEqual(parse_resolv_conf("# only a comment\n"), [])


class LoadUpstreamTests(unittest.TestCase):
    def test_direct_upstreams_preferred(self):
        with make_layout() as (base, host_etc, run_systemd, _):
            (host_etc / "resolv.conf").write_text(
                "nameserver 192.168.1.1\nnameserver 100.100.100.100\n"
            )
            (run_systemd / "resolv.conf").write_text("nameserver 9.9.9.9\n")
            self.assertEqual(
                upstreams_of(host_etc, base),
                ["192.168.1.1", "100.100.100.100"],
            )

    def test_stub_symlink_falls_back_to_systemd_uplinks(self):
        # Mirrors systemd-resolved: /etc/resolv.conf -> stub file with the
        # loopback stub, real upstreams in /run/systemd/resolve/resolv.conf.
        with make_layout() as (base, host_etc, run_systemd, _):
            stub = run_systemd / "stub-resolv.conf"
            stub.write_text("nameserver 127.0.0.53\noptions edns0 trust-ad\n")
            os.symlink(stub, host_etc / "resolv.conf")
            (run_systemd / "resolv.conf").write_text(
                "nameserver 192.168.1.1\nnameserver 8.8.8.8\n"
            )
            self.assertEqual(
                upstreams_of(host_etc, base), ["192.168.1.1", "8.8.8.8"]
            )

    def test_absolute_run_symlink_target_stays_remapped(self):
        # A host symlink with an absolute /run target must resolve under the
        # /host/run bind, not the sidecar's own /run (which has no such file
        # and must never be trusted as host state).
        with make_layout() as (base, host_etc, run_systemd, _):
            stub = base / "run" / "systemd" / "resolve" / "stub-resolv.conf"
            stub.write_text("nameserver 127.0.0.53\n")
            os.symlink(
                "/run/systemd/resolve/stub-resolv.conf", host_etc / "resolv.conf"
            )
            (run_systemd / "resolv.conf").write_text("nameserver 192.168.7.1\n")
            self.assertEqual(upstreams_of(host_etc, base), ["192.168.7.1"])

    def test_symlink_escaping_the_binds_yields_nothing(self):
        with make_layout() as (base, host_etc, _, _):
            os.symlink("/usr/share/doc/example", host_etc / "resolv.conf")
            self.assertEqual(upstreams_of(host_etc, base), [])

    def test_networkmanager_fallback_when_no_systemd(self):
        with make_layout() as (base, host_etc, _, run_nm):
            (host_etc / "resolv.conf").write_text("nameserver 127.0.0.1\n")
            (run_nm / "resolv.conf").write_text("nameserver 192.168.2.1\n")
            self.assertEqual(upstreams_of(host_etc, base), ["192.168.2.1"])

    def test_no_stub_fallback_for_caching_plugin(self):
        # With a caching plugin NM's resolv.conf repeats the loopback cache;
        # the actual uplinks live in no-stub-resolv.conf.
        with make_layout() as (base, host_etc, _, run_nm):
            (host_etc / "resolv.conf").write_text("nameserver 127.0.0.1\n")
            (run_nm / "resolv.conf").write_text("nameserver 127.0.0.1\n")
            (run_nm / "no-stub-resolv.conf").write_text(
                "nameserver 192.168.3.1\n"
            )
            self.assertEqual(upstreams_of(host_etc, base), ["192.168.3.1"])

    def test_no_stub_takes_precedence_over_nm_resolv(self):
        with make_layout() as (base, host_etc, _, run_nm):
            (host_etc / "resolv.conf").write_text("nameserver 127.0.0.1\n")
            (run_nm / "no-stub-resolv.conf").write_text(
                "nameserver 192.168.3.1\n"
            )
            (run_nm / "resolv.conf").write_text("nameserver 192.168.2.1\n")
            self.assertEqual(upstreams_of(host_etc, base), ["192.168.3.1"])

    def test_loopback_only_with_no_uplinks_yields_nothing(self):
        # Forwarding to 127.0.0.53 from inside the sidecar would hit the
        # sidecar itself; never return loopback, and never invent public DNS.
        with make_layout() as (base, host_etc, _, _):
            (host_etc / "resolv.conf").write_text("nameserver 127.0.0.53\n")
            self.assertEqual(upstreams_of(host_etc, base), [])

    def test_missing_files_yield_nothing(self):
        with make_layout() as (base, host_etc, _, _):
            self.assertEqual(upstreams_of(host_etc, base), [])


class TrackerTests(unittest.TestCase):
    def _tracker(self, host_etc, base):
        return UpstreamTracker(str(host_etc), str(base / "run"))

    def test_atomic_replace_is_picked_up(self):
        with make_layout() as (base, host_etc, _, _):
            (host_etc / "resolv.conf").write_text("nameserver 192.168.1.1\n")
            tracker = self._tracker(host_etc, base)
            self.assertEqual(tracker.poll(), ["192.168.1.1"])
            self.assertIsNone(tracker.poll())
            # Atomic rewrite: write temp, rename over (as NetworkManager does).
            fresh = host_etc / "resolv.conf.new"
            fresh.write_text("nameserver 192.168.1.9\n")
            os.replace(fresh, host_etc / "resolv.conf")
            self.assertEqual(tracker.poll(), ["192.168.1.9"])
            self.assertIsNone(tracker.poll())

    def test_symlink_swap_is_picked_up(self):
        with make_layout() as (base, host_etc, _, _):
            wifi_a = host_etc / "resolv.wifi-a"
            wifi_b = host_etc / "resolv.wifi-b"
            wifi_a.write_text("nameserver 10.1.0.1\n")
            wifi_b.write_text("nameserver 10.2.0.1\n")
            os.symlink("resolv.wifi-a", host_etc / "resolv.conf")
            tracker = self._tracker(host_etc, base)
            self.assertEqual(tracker.poll(), ["10.1.0.1"])
            os.unlink(host_etc / "resolv.conf")
            os.symlink("resolv.wifi-b", host_etc / "resolv.conf")
            self.assertEqual(tracker.poll(), ["10.2.0.1"])

    def test_unusable_replacement_clears_upstreams(self):
        # A resolver change to nothing usable must clear the old addresses,
        # not keep serving stale servers as if split DNS still worked.
        with make_layout() as (base, host_etc, _, _):
            (host_etc / "resolv.conf").write_text("nameserver 192.168.1.1\n")
            tracker = self._tracker(host_etc, base)
            self.assertEqual(tracker.poll(), ["192.168.1.1"])
            (host_etc / "resolv.conf").write_text("# transiently empty\n")
            self.assertEqual(tracker.poll(), [])
            self.assertEqual(tracker.current, [])
            self.assertIsNone(tracker.poll())


if __name__ == "__main__":
    unittest.main()
