{{- if not .Values.webserver.hostNetwork }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chatbot.fullname" . }}-webserver
  labels:
    {{- include "chatbot.labels" . | nindent 4 }}
    app.kubernetes.io/component: webserver
spec:
  type: {{ .Values.webserver.service.type }}
  selector:
    {{- include "chatbot.labels" . | nindent 4 }}
    app.kubernetes.io/component: webserver
  ports:
    - name: http
      port: {{ .Values.webserver.service.port }}
      targetPort: http
{{- end }}